namespace TGCCaddy.Model
{
    public interface IWindAdjuster
    {
        /// <summary>
        /// Gets the distance generated by the wind
        /// </summary>
        int GetWindDistance(int distance);

        /// <summary>
        /// Gets the distance and adjusts it according to the wind
        /// </summary>
        int GetWindAdjustedDistance(int distance);

        /// <summary>
        /// Determines whether the wind is altered by elevation
        /// </summary>
        bool AdjustForElevation { get; set; }
    }
}